name: copd-paper
channels:
    - defaults
dependencies:
    - dask=2.10.1
    - matplotlib=3.1.2
    - numpy=1.16.2
    - pandas=1.0.1
    - pip=19.3.1
    - python=3.7.6
    - scipy=1.3.1
    - pip:
        - ciw==2.0.1
